# Default values for yaml.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.



#///////////////////////////MOVIE SERVICE////////////////////////
movieService:
 
  image:
    repository: sebdevops06/movie-service
    pullPolicy: IfNotPresent
    # Overrides the image tag whose default is the chart appVersion.
    tag: "latest"

  service:
    type: ClusterIP
    port: 8000
    targetPort: 8000
    clusterIP: 10.43.140.113

  ingress:
    className: "traefik"
    annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
    rules:
      host: jenkins.seb-cours-datascientest.cloudns.eu
      paths:
        path: /users
        pathType: Prefix
      port: 5000
    tls: 
      secretName: fastapi-secret
      hosts: jenkins.seb-cours-datascientest.cloudns.eu
#///////////////////////////<MOVIE DB////////////////////////
movieDb:

  image:
    repository: postgres
    pullPolicy: IfNotPresent
    # Overrides the image tag whose default is the chart appVersion.
    tag: "12.0-alpine"
  
  service: 
    type: ClusterIP
    port: 5432
    targetPort: 5432
    clusterIP: 10.43.140.113
  volume:
    hostPath: /mnt/movie-data
    mountPath: /var/lib/postgresql/data/
  
#///////////////////////////CAST SERVICE////////////////////////
castService:
  image:
    repository: sebdevops06/cast-service
    pullPolicy: IfNotPresent
    # Overrides the image tag whose default is the chart appVersion.
    tag: "latest"

  service: 
    type: ClusterIP
    clusterIP: 10.43.5.10
    port: 8000
    targetPort: 8000
  
  volume:
    hostPath: /mnt/data
    mountPath: /var/lib/postgresql/data/
    
  
#///////////////////////////CAST DB////////////////////////
castDb:
  image:
    repository: postgres:12.0-alpine
    pullPolicy: IfNotPresent
    # Overrides the image tag whose default is the chart appVersion.
    tag: 12.0-alpine

  service: 
    type: ClusterIP
    clusterIP: 10.43.5.10
    port: 5432
    targetPort: 5432
  volume:
    hostPath: /mnt/cast-data
    mountPath: /var/lib/postgresql/data/
    
    