# Default values for yaml.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.


namespace: helm
#///////////////////////////FAST API////////////////////////
fastapi:
  minReplicas: 3
  maxReplicas: 6
  targetCPU: 70

  image:
    repository: sebdevops06/fastapik3s
    pullPolicy: IfNotPresent
    # Overrides the image tag whose default is the chart appVersion.
    tag: "latest"

  service:
    type: ClusterIP
    port: 5000
    targetPort: 5000
    clusterIP: 10.43.140.113

  ingress:
    className: "traefik"
    annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
    rules:
      host: app1.seb-cours-datascientest.cloudns.eu
      paths:
        path: /users
        pathType: Prefix
      port: 5000
    tls: 
      secretName: fastapi-secret
      hosts: app1.seb-cours-datascientest.cloudns.eu
#///////////////////////////PG ADMIN////////////////////////
pgadmin:
  replicaCount: 1

  image:
    repository: dpage/pgadmin4
    pullPolicy: IfNotPresent
    # Overrides the image tag whose default is the chart appVersion.
    tag: "latest"
  
  service: 
    type: NodePort
    port: 80
    targetPort: 80
    nodePort: 30000

  env:
    pgAdminEmail: admin@admin.com
    pgAdminPass: root
#///////////////////////////POSTGRES////////////////////////
postgres:
  replicaCount: 1
  image:
    repository: postgres
    pullPolicy: IfNotPresent
    # Overrides the image tag whose default is the chart appVersion.
    tag: "12.0-alpine"

  service: 
    type: ClusterIP
    clusterIP: 10.43.5.10
    port: 5432
    targetPort: 5432
  
  volume:
    hostPath: /mnt/data
    mountPath: /var/lib/postgresql/data/
    
  env: 
    postgresUser: admin
    postgresPass: password
    postgresDB: storedb
    postgresHost: trust
