
apiVersion: apps/v1
kind: Deployment
metadata:
 name: {{.Release.Name }}{{.Release.Namespace }}-cast
 #namespace: yaml
spec:
 selector:
   matchLabels:
     app: {{.Release.Name }}{{.Release.Namespace }}-cast
 template:
   metadata:
     labels:
       app: {{.Release.Name }}{{.Release.Namespace }}-cast
   spec:
    containers:
      - name: {{.Release.Name }}{{.Release.Namespace }}-cast
        image: {{.Values.castService.image.repository}}:{{.Values.castService.image.tag}}
        imagePullPolicy: Always

        ports:
        - containerPort: {{.Values.castService.service.port}}
          name: cast-http
        env:
        - name: DATABASE_URI
          value: postgresql://cast_db_username:cast_db_password@{{.Release.Name }}-cast-db/cast_db_dev
     
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{.Release.Name }}{{.Release.Namespace }}-cast
  name: {{.Release.Name }}{{.Release.Namespace }}-cast
  #namespace: yaml
spec:
  selector:
    app: {{.Release.Name }}{{.Release.Namespace }}-cast
  type: {{.Values.castService.service.type}}
  #clusterIP: {{.Values.castService.service.clusterIP}}
  ports:
  - name : cast-http
    protocol: TCP
    port: {{.Values.castService.service.port}}
    targetPort: {{.Values.castService.service.port}}