
apiVersion: apps/v1
kind: Deployment
metadata:
 name: {{.Release.Name }}-cast
 #namespace: yaml
spec:
 selector:
   matchLabels:
     app: {{.Release.Name }}-cast
 template:
   metadata:
     labels:
       app: {{.Release.Name }}-cast
   spec:
    containers:
      - name: {{.Release.Name }}-cast
        image: {{.Values.castService.image.repository}}:{{.Value.castService.image.tag}}
        imagePullPolicy: Always

        ports:
        - containerPort: {{.Values.castService.service.port}}
          name: cast-http
        env:
        - name: DATABASE_URI
          value: "postgresql://cast_db_username:cast_db_password@"{{.Release.Name }}"-cast-db/cast_db_dev"
     
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{.Release.Name }}-cast
  name: {{.Release.Name }}-cast
  #namespace: yaml
spec:
  selector:
    app: {{.Release.Name }}-cast
  type: {{.Values.castService.service.type}}
  clusterIP: {{.Values.castService.service.clusterIP}}
  ports:
  - name : cast-http
    protocol: TCP
    port: {{.Values.castService.service.port}}
    targetPort: {{.Values.castService.service.port}}