
apiVersion: apps/v1
kind: Deployment
metadata:
 name: {{.Release.Name }}-movie
 #namespace: yaml
spec:
 selector:
   matchLabels:
     app: {{.Release.Name }}-movie
 template:
   metadata:
     labels:
       app: {{.Release.Name }}-movie
   spec:
    containers:
      - name: {{.Release.Name }}-movie
        image: {{.Values.movieService.image.repository }}:{{.Values.movieService.image.tag}}
        imagePullPolicy: Always

        ports:
        - containerPort: {{.Values.movieService.service.port }}
          name: {{.Release.Name }}-movie
        env:
        - name: DATABASE_URI
          value: "postgresql://movie_db_username:movie_db_password@movie_db/movie_db_dev"
        - name: CAST_SERVICE_HOST_URL
          value: "http://jenkins.seb-cours-datascientest.cloudns.eu/api/v1/casts/"
---        
apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{.Release.Name }}-movie
  name: {{.Release.Name }}-movie
  #namespace: yaml
spec:
  selector:
    app: {{.Release.Name }}-movie
  type: {{.Values.movieService.service.type }}
  clusterIP: {{.Values.movieService.service.clusterIP }}
  ports:
  - name : {{.Release.Name }}-movie
    protocol: TCP
    port: {{.Values.movieService.service.port }}
    targetPort: {{.Values.movieService.service.port }}