apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{.Release.Namespace }}-movie-pv
  labels:
    type: local
  #namespace: yaml
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: {{.Values.movieDb.volume.hostPath}}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{.Release.Namespace }}-movie-pvc
  #namespace: yaml
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: manual
  resources:
    requests:
      storage: 2Gi
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{.Release.Namespace }}-movie-db-config
  labels:
    app: {{.Release.Namespace }}-movie-db-config
data:
  POSTGRES_DB: {{.Values.env.moviedb}}
  POSTGRES_USER: {{.Values.env.user}}
  POSTGRES_PASSWORD: {{.Values.env.password}}
  PGDATA: /var/lib/postgresql/data
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
 name: {{.Release.Namespace }}-movie-db
 labels:
   app: {{.Release.Namespace }}-movie-db
 #namespace: yaml
spec:
  selector:
    matchLabels:
      app: {{.Release.Namespace }}-movie-db
  serviceName: {{.Release.Namespace }}-movie-db
  replicas: 1
  template:
   metadata:
     labels:
       app: {{.Release.Namespace }}-movie-db
   spec:
    volumes:
    - name: {{.Release.Namespace }}-movie-pod-storage
      persistentVolumeClaim:
        claimName: {{.Release.Namespace }}-movie-pvc
    containers:
    - name: {{.Release.Namespace }}-movie-container
      image: postgres:12.1-alpine
     # envFrom:
      #- configMapRef:
       #   name: {{.Release.Namespace }}-movie-db-config
      ports:
      - containerPort: {{.Values.movieDb.service.port}}
        name: {{.Release.Namespace }}movie-db
      volumeMounts:
        - mountPath: {{.Values.movieDb.volume.mountPath}}
          name: {{.Release.Namespace }}-movie-pod-storage
      env:
      - name: POSTGRES_USER
        value: {{.Values.env.user}}
      - name: POSTGRES_PASSWORD
        value: {{.Values.env.password}}
      - name: POSTGRES_DB
        value: {{.Values.env.moviedb}}
      
---
apiVersion: v1
kind: Service
metadata:
  name: {{.Release.Namespace }}-movie-db
  #namespace: yaml
spec:
  selector:
    app: {{.Release.Namespace }}-movie-db
  #type: {{.Values.movieDb.service.type}}
  #clusterIP: {{.Values.movieDb.service.clusterIP}}
  ports:
  - name: {{.Release.Namespace }}-movie-db
    protocol: TCP
    port: {{.Values.movieDb.service.port}}
    targetPort: {{.Values.movieDb.service.port}}
