
apiVersion: apps/v1
kind: Deployment
metadata:
 name: {{.Release.Name }}{{.Release.Namespace }}-movie
 #namespace: yaml
spec:
 selector:
   matchLabels:
     app: {{.Release.Name }}{{.Release.Namespace }}-movie
 template:
   metadata:
     labels:
       app: {{.Release.Name }}{{.Release.Namespace }}-movie
   spec:
    containers:
      - name: {{.Release.Name }}{{.Release.Namespace }}-movie
        image: {{.Values.movieService.image.repository }}:{{.Values.movieService.image.tag}}
        imagePullPolicy: Always

        ports:
        - containerPort: {{.Values.movieService.service.port }}
          name: {{.Release.Namespace }}-movie
        env:
        - name: DATABASE_URI
          value: "postgresql://admin:root@{{.Release.Name }}{{.Release.Namespace }}-movie-db/movie_db_{{.Release.Namespace }}"
        - name: CAST_SERVICE_HOST_URL
          value: "https://jenkins.seb-cours-datascientest.cloudns.eu/api/v1/casts/"
---        
apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{.Release.Name }}{{.Release.Namespace }}-movie
  name: {{.Release.Name }}{{.Release.Namespace }}-movie
  #namespace: yaml
spec:
  selector:
    app: {{.Release.Name }}{{.Release.Namespace }}-movie
  type: {{.Values.movieService.service.type }}
  #clusterIP: {{.Values.movieService.service.clusterIP }}
  ports:
  - name : movie-http
    protocol: TCP
    port: {{.Values.movieService.service.port }}
    targetPort: {{.Values.movieService.service.port }}