apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{.Release.Name }}{{.Release.Namespace }}-movie-pv
  labels:
    type: local
  #namespace: yaml
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: {{.Values.movieDb.volume.hostPath}}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{.Release.Name }}-movie-pvc
  #namespace: yaml
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: manual
  resources:
    requests:
      storage: 2Gi
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
 name: {{.Release.Name }}-movie-db
 labels:
   app: {{.Release.Name }}-movie-db
 #namespace: yaml
spec:
  selector:
    matchLabels:
      app: {{.Release.Name }}-movie-db
  serviceName: {{.Release.Name }}-movie-db
  replicas: 1
  template:
   metadata:
     labels:
       app: {{.Release.Name }}-movie-db
   spec:
    volumes:
    - name: movie-pod-storage
      persistentVolumeClaim:
        claimName: {{.Release.Name }}-movie-pvc
    containers:
    - name: {{.Release.Name }}-movie-container
      image: {{.Values.movieDb.image.repository }}:{{.Values.movieDb.image.tag }}
   
      ports:
      - containerPort: {{.Values.movieDb.service.port}}
        name: {{.Release.Name }}-movie-db
      volumeMounts:
        - mountPath: {{.Values.movieDb.volume.mountPath}}
          name: movie-pod-storage
      env:
      - name: POSTGRES_USER
        value: "movie_db_username"
      - name: POSTGRES_PASSWORD
        value: "movie_db_password"
      - name: POSTGRES_DB
        value: "movie_db_dev"
      - name: POSTGRES_HOST_AUTH_METHOD
        value: "trust"
---
apiVersion: v1
kind: Service
metadata:
  name: {{.Release.Name }}-movie
  #namespace: yaml
spec:
  selector:
    app: {{.Release.Name }}-movie-db
  type: {{.Values.movieDb.service.type}}
  #clusterIP: {{.Values.movieDb.service.clusterIP}}
  ports:
  - name: movie-db
    protocol: TCP
    port: {{.Values.movieDb.service.port}}
    targetPort: {{.Values.movieDb.service.port}}
