apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-yaml
  labels:
    type: local
  namespace: yaml
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/movie-data"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-yaml
  namespace: yaml
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: manual
  resources:
    requests:
      storage: 2Gi
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
 name: db
 labels:
   app: db
 namespace: yaml
spec:
  selector:
    matchLabels:
      app: db
  serviceName: db
  replicas: 1
  template:
   metadata:
     labels:
       app: db
   spec:
    volumes:
    - name: yaml-pod-storage
      persistentVolumeClaim:
        claimName: pvc-yaml
    containers:
    - name: db-container
      image: postgres:12.0-alpine
   
      ports:
      - containerPort: 5432
        name: db
      volumeMounts:
        - mountPath: /var/lib/postgresql/data/
          name: yaml-pod-storage
      env:
      - name: POSTGRES_USER
        value: "movie_db_username"
      - name: POSTGRES_PASSWORD
        value: "movie_db_password"
      - name: POSTGRES_DB
        value: "movie_db_dev"
      - name: POSTGRES_HOST_AUTH_METHOD
        value: "trust"
---
apiVersion: v1
kind: Service
metadata:
  name: db-clusterip
  namespace: yaml
spec:
  selector:
    app: db
  type: ClusterIP
  clusterIP: 10.43.6.10
  ports:
  - name: db
    protocol: TCP
    port: 5432
    targetPort: 5432
